config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/components', to: 'pages#components'
  resources :activities, except: [:index]
  resources :bookings

  get '/profile/my_bookings', to: 'bookings#my_bookings'
  get '/profile/my_bookings/:id', to: 'bookings#show', as: :my_booking

  get '/invitation', to: 'bookings#invitation', as: :invitation

  get '/profile/my_bookings/:booking_id/reviews/new', to: 'reviews#new', as: :new_review
  post'/profile/my_bookings/:booking_id/reviews/', to: 'reviews#create', as: :create_review
  delete '/profile/reviews/:id', to: 'reviews#destroy', as: :destroy_review

  get '/custom_activity', to: 'pages#custom_activity', as: :custom_activity
  get '/random', to: 'pages#random'
  get '/select', to: 'pages#select'
  get '/no_activity', to: 'pages#no_activity', as: :no_activity

  get '/activity/:id', to: 'activities#show' do
    resources :bookings, only: [:new, :create]
  end
  delete '/profile/my_bookings', to: 'bookings#destroy'
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :slot
  belongs_to :user
  has_one :review, dependent: :destroy
  has_many :notifications

  validates :number_of_people, presence: true
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
before_action :authenticate_user!, only: :new

  def my_bookings
    if params[:notification]
      @notification = Notification.find(params[:notification])
      @notification.read = true
      @notification.save!
      # @counter = params[:counter].to_i - 1
      @counter = current_user.notifications.where(read: false).count

    end
    @my_bookings = Booking.where(user_id: current_user.id).order(created_at: :desc)
    @my_bookings_reviewed = []
    @my_bookings_to_review = []
    @my_bookings.each do |booking|
      if booking.review.nil?
        @my_bookings_to_review << booking
      else
        @my_bookings_reviewed << booking
      end
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @guests = "ta copine, ton partenaire, ton chien, ta mamie, ton amoureuse, Rémi Carette"
  end

  def new
  end

  def invitation
    @booking = Booking.find(params[:guest][:booking])
    GuestMailer.with(current_user).invitation(params[:email], @booking).deliver_now
    redirect_to profile_my_bookings_path
  end

  def create
    @activity = Activity.find(params[:activity_id])
    @reveal = params[:reveal]
    @booking = Booking.new
    @booking[:number_of_people] = params[:nb_people]
    @slot = @activity.slots.first
    @booking.user = current_user
    @booking.slot = @slot
    @booking.reveal = @reveal
    @booking.save
    redirect_to my_booking_path(@booking)
  end

  private

  def booking_params
    params.require(:booking).permit(:slot_id, :user_id, :reveal)
  end
end

app/views/bookings/_mystery_show.html.erb
<div class="written-activity-booked mood-form" id="resa-faite">
  <div class="text-center">
    <h2 class="mt-3">Ta réservation est faite !</h2>
    <p>Tu recevras un email de confirmation sous peu !</p>
  </div>

  <% if (@booking.number_of_people == 2) %>
    <div class="invite-guest card box-shadow">
    
      <div class="guest-sentence">
        <p id="guest-line">Envoie une invitation mystère à 
        <span id="guest-text" data-guests="<%= @guests %>" ></span> ?</p>
      </div>
      <%# <div class="text-center mb-5"> %>
        <%# <%= image_tag "arrow.png", class: "arrow" %>

          <div class="text-center">
            <%= simple_form_for :guest, url: invitation_path, class: "text-center guest-email", method: "get" do |f| %>
              <%= f.hidden_field :booking, value: @booking.id %>
              <%= f.text_field :guest_mail, id: "guest-email-input", name: "email", value: "", placeholder: "email", required: true %>
              <%= f.submit "Inviter ! ", class: "my-btn my-btn-primary mt-3", id:"submit-btn" %>
            <% end %>
          </div>

      </div>

    </div>
  <% end %>

</div>


<div class="my-button-invitation">
  <div class="form-actions my-tap-container" id="margin-top">
    <%= link_to 'Mes réservations', profile_my_bookings_path, class: "my-btn my-btn-primary", id: "arrow-issue" %>
  </div>
</div>

app/views/bookings/_reveal_show.html.erb
<div class="card-activity text-center">
    <%= cl_image_tag @booking.slot.activity.photos[0].key, crop: :fill, class: "cover" %>
  </div>

<%= render "mystery_show" %>

app/views/bookings/booking_cards.html.erb
<div class="placholder-navbar" style="height:66px"></div>

app/views/bookings/my_bookings.html.erb
<div class="placholder-navbar" style="height:66px"></div>

<div class="my-container" id='bookings-container'>
  <h2>Mes réservations </h2>
  <p class="text-center">(<%= @my_bookings.count %> dont <%= @my_bookings_to_review.count %> à noter)</p> 
  <% @my_bookings.each do |booking| %>
    <% if booking.reveal %>
      <div class="my-card my-activity-card box-shadow" id='<%= booking.slot.end_date %>'>
    <% else %>
      <div class="my-card my-activity-card box-shadow activity-secret" id='<%= booking.slot.end_date %>'>
    <% end %>
        <div class="my-card-div-image">
          <div class="display-over d-flex justify-content-between">
            <% if booking.review %>
              <div>
                <% if [1, 2, 3, 4, 5].include?(booking.review.rating) %>
                  <% booking.review.rating.to_i.times do %>
                    <i class="fas fa-star"></i>
                  <% end %>
                  <% (5 - booking.review.rating.to_i).times do %>
                    <i class="far fa-star"></i>
                  <% end %>
                <% else %>
                  <% booking.review.rating.to_f.truncate.times do %>
                    <i class="fas fa-star"></i>
                  <% end %>
                  <i class="fas fa-star-half-alt"></i>
                  <% (4 - booking.review.rating.to_f.truncate).times do %>
                    <i class="far fa-star"></i>
                  <% end %>
                <% end %>
              </div>
            <% else %>
              <div>
                <button class = "my-btn-review" href='#myModal<%=booking.id%>'> Donne ton avis </button>
              </div>
              <!-- The Modal -->
              <div class="modal" id='myModal<%=booking.id%>'>
                <!-- Modal content -->
                <div class="modal-content">
                  <div class = "my-card-div-details d-flex justify-content-between">
                    <div class="hide-name"></div>
                    <h4> <%= booking.slot.activity.name %> </h4>
                    <span class="close">&times;</span>
                    </div>
                  <%= render '/reviews/new', booking: booking %>
                </div>
              </div>
            <% end %>
            <% if booking.slot.activity.instructions %>
              <div class="icon-info" id="#info<%=booking.id%>"></div>
              <div class = "activity-informations display-none" id="info<%=booking.id%>">
                <% if booking.review %>
                Ton avis: <%= booking.review.content %>
                <hr>
                <% end %>
                <%= booking.slot.activity.instructions %>
              </div>
            <% end %>
          </div>
          <div class="div-image-overlay">
            <p>?</p>
          </div>
          <%= cl_image_tag booking.slot.activity.photos[0].key, crop: :fill %>
        </div>
        <div class="my-card-div-details display-flex-column">
          <div class="hide-name"></div>
          <h3> <%= booking.slot.activity.name %> </h3>
          <div class="display-flex">

            <div class="display-flex-column">
              <div class="card-detail">
                <i class="fas fa-euro-sign"></i>
                <p> <%= booking.slot.activity.price_per_head %> (par personne)</p>
              </div>
              <div class="card-detail">
                <i class="fas fa-hourglass-start"></i>
                <p>environ 2h</p>
              </div>
            </div>
            <div class="display-flex-column">
              <div class="card-detail">
                <i class="fas fa-map-marker-alt"></i>
                <p>à 7km</p>
              </div>
              <div class="card-detail">
                <i class="fas fa-clock"></i>
                <p>rdv à 19h30</p>
              </div>
            </div>
          </div>
        </div>
      </div>
  <% end %>
</div>

<div class="my-tap-container" id="remove-fixed">
  <%= link_to 'Randomize!', random_path, :class => 'my-btn my-btn-primary' %>
</div>

app/views/bookings/show.html.erb
<div class="placholder-navbar" style="height:66px"></div>

<div class="my-container">
  <% if @booking.reveal == true %>
    <%= render "bookings/reveal_show", booking: @booking, guests: @guests %>
  <% else %>
    <%= render "bookings/mystery_show", booking: @booking, guests: @guests %>
  <% end %>
</div>
<!-- secret: class="my-card my-activity-card box-shadow activity-secret"
pas sercret: class="my-card my-activity-card box-shadow" -->