config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/components', to: 'pages#components'
  resources :activities, except: [:index]
  resources :bookings

  get '/profile/my_bookings', to: 'bookings#my_bookings'
  get '/profile/my_bookings/:id', to: 'bookings#show', as: :my_booking

  get '/invitation', to: 'bookings#invitation', as: :invitation

  get '/profile/my_bookings/:booking_id/reviews/new', to: 'reviews#new', as: :new_review
  post'/profile/my_bookings/:booking_id/reviews/', to: 'reviews#create', as: :create_review
  delete '/profile/reviews/:id', to: 'reviews#destroy', as: :destroy_review

  get '/custom_activity', to: 'pages#custom_activity', as: :custom_activity
  get '/random', to: 'pages#random'
  get '/select', to: 'pages#select'
  get '/no_activity', to: 'pages#no_activity', as: :no_activity

  get '/activity/:id', to: 'activities#show' do
    resources :bookings, only: [:new, :create]
  end
  delete '/profile/my_bookings', to: 'bookings#destroy'
end

app/views/shared/_banner.html.erb
<div class="banner" style="">
  <div class="my-container">
    <div class="banner-content">  
      <h1>Envie de découverte?</h1>
      <div class="space-button">
        <h3 style = "color: #f4f4f4">Aujourd'hui, c'est
          <span id="banner-typed-text" data-activities="<%= @activities_names %>" ></span>
        </h3>
      </div>
      <div id="banner-button">
        <%= link_to "Randomize!", random_path, class: 'my-btn my-btn-primary' %> 
      </div>
    </div>
  </div>
</div>

app/views/shared/_components.html.erb
<%# All components here %>

<h2>Button primary</h2>
<a href="#" class="my-btn my-btn-primary">Primary</a>

<h2>Button primary tap</h2>
<%# Remove display none to see %>
<div class="my-tap-container  display-none">
  <a href="#" class="my-btn btn-primary">Primary</a>
</div>

<h2>Button secondary</h2>
<a href="#" class="my-btn my-btn-secondary">Secondary</a>

<h2>Button secondary tap</h2>
<%# Remove display none to see %>
<div class="my-tap-container  display-none">
  <a href="#" class="my-btn my-btn-secondary">Secondary</a>
</div>

<h2>Button primary tap + secondary tap</h2>
<%# Remove display none to see %>
<div class="my-tap-container display-none">
  <a href="#" class="my-btn my-btn-secondary my-btn-top-left-radius">Secondary</a>
  <a href="#" class="my-btn my-btn-primary my-btn-tap my-btn-top-right-radius">Primary</a>
</div>

<h2>Activity card</h2>

<h3>Revealed</h3>

<div class="my-card my-activity-card box-shadow">
  <div class="my-card-div-image">
    <div class="div-image-overlay">
    </div>
    <%= cl_image_tag Activity.last.photos[0].key, crop: :fill %>
    <div class="icon-info"><p>i</p></div>
  </div>
  <div class="my-card-div-details display-flex-column">
    <h3>Padel (niveau loisir)</h3>
    <div class="display-flex">

      <div class="display-flex-column">
        <div class="card-detail">
          <i class="fas fa-euro-sign"></i>
          <p>10 (par personne)</p>
        </div>
        <div class="card-detail">
          <i class="fas fa-hourglass-start"></i>
          <p>environ 2h</p>
        </div>
      </div>

      <div class="display-flex-column">
        <div class="card-detail">
          <i class="fas fa-map-marker-alt"></i>
          <p>à 7km</p>
        </div>
        <div class="card-detail">
          <i class="fas fa-clock"></i>
          <p>rdv à 19h30</p>
        </div>
      </div>
    </div>
  </div>
</div>

<h3>Hidden</h3>

<div class="my-card my-activity-card box-shadow activity-secret">
  <div class="my-card-div-image">
    <div class="div-image-overlay">
      <p>?</p>
      <a href="#" class="my-btn my-btn-reveal">Révéler</a>
    </div>
    <%= cl_image_tag Activity.last.photos[0].key, crop: :fill %>
    <div class="icon-info"><p>i</p></div>
  </div>
  <div class="my-card-div-details display-flex-column">
    <h3>Padel (niveau loisir)</h3>
    <div class="display-flex">

      <div class="display-flex-column">
        <div class="card-detail">
          <i class="fas fa-euro-sign"></i>
          <p>10 (par personne)</p>
        </div>
        <div class="card-detail">
          <i class="fas fa-hourglass-start"></i>
          <p>environ 2h</p>
        </div>
      </div>

      <div class="display-flex-column">
        <div class="card-detail">
          <i class="fas fa-map-marker-alt"></i>
          <p>à 7km</p>
        </div>
        <div class="card-detail">
          <i class="fas fa-clock"></i>
          <p>rdv à 19h30</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
  </div>
  <div class="footer-copyright">
    This app was made with <i class="fas fa-heart"></i> by Randomize
  </div>
</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-randomize fixed-top">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "Logo.png" %>
    <% end %>

  <%# <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <i class="fas fa-bars"></i>
  </button> %>


  <div class="my-navbar" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto navbar-ul">
      <% if user_signed_in? %>
        <div class="notifications">



          <li class="nav-item">
            <i class="fas fa-bell bell"></i>
              <% if @counter.to_i > 0 %>
                <div class="notification-number">
                  <%= @counter %>
                </div>
              <% end %>
            <% if @counter.to_i > 0 %>
              <div id="my-menu-notifications" class="drop-menu display-none" aria-labelledby="">
                <% categories =  ["feedback", "welcome", "reminder"] %>
                <% categories.each do |cat| %>
                  <% unless current_user.notifications.where(category: cat).empty? %>
                    <div id= "clicked-event" >
                      <% @read_notification = current_user.notifications.where(category: cat, read: false).order(:created_at) %>
                      <% @read_notification.each do |notification| %>
                        <%= link_to notification.content, profile_my_bookings_path(notification: notification, counter: @counter) %>
                      <% end %>
                      <!-- link_to @read_notification.content, profile_my_bookings_path(:notification => @read_notification, counter: @counter) -->
                    </div>
                  <% end %>
                <% end %>
              </div>
            <% end %>
          </li>
        </div>
        <li class="nav-item dropdown">
          <% if current_user.photo.present? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "Profile.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div id="my-menu-profile" class="drop-menu display-none" aria-labelledby="">
            <%= link_to "Mes réservations", profile_my_bookings_path, class: "dropdown-item" %>
            <%= link_to "Me déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Me connecter", new_user_session_path, class: "nav-link", id: "navbar-light" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar_draft.html.erb
<div class="navbar">
  <div>
    <%= link_to "#home", class: "navbar-logo" do %>
      <%= image_tag "Logo.png" %>
      <% end %>
  </div>

  <div class="flex-icons">
    <% if user_signed_in? %>
      <i class="fas fa-bell bell"></i>
      <i class="fas fa-circle circle"></i>
    <div class="stick-icons">
      <% if current_user.photo.present? %>
        <%= cl_image_tag current_user.photo.key %>
      <% else %>
        <%= image_tag "Profile", class: "avatar"%>
      <% end %>
    </div>
    <% else %>
      <div class="nav-item">
        <%= link_to "Login", new_user_session_path %>
      </div>
    <% end %>
  </div>
</div>