config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/components', to: 'pages#components'
  resources :activities, except: [:index]
  resources :bookings

  get '/profile/my_bookings', to: 'bookings#my_bookings'
  get '/profile/my_bookings/:id', to: 'bookings#show', as: :my_booking

  get '/invitation', to: 'bookings#invitation', as: :invitation

  get '/profile/my_bookings/:booking_id/reviews/new', to: 'reviews#new', as: :new_review
  post'/profile/my_bookings/:booking_id/reviews/', to: 'reviews#create', as: :create_review
  delete '/profile/reviews/:id', to: 'reviews#destroy', as: :destroy_review

  get '/custom_activity', to: 'pages#custom_activity', as: :custom_activity
  get '/random', to: 'pages#random'
  get '/select', to: 'pages#select'
  get '/no_activity', to: 'pages#no_activity', as: :no_activity

  get '/activity/:id', to: 'activities#show' do
    resources :bookings, only: [:new, :create]
  end
  delete '/profile/my_bookings', to: 'bookings#destroy'
end

app/views/pages/components.html.erb
<div class="container">
  <h1>Components</h1>
  <%= render 'shared/components' %>
</div>

app/views/pages/custom_activity.html.erb
<div class="placholder-navbar" style="height:66px"></div>

<div class="my-container">
  <div class="sorry" id="">
    <h1>DÉSOLÉ ... </h1>

  <div class="text-center">
    <%= image_tag "alone.png", class: "alone" %>
  </div>

  <div class="mood-sentence">
    <h3>Aucune activité ne correspond à tes critères</h3>
    <div class="margin-top">
      <p>Réessaye ici</p>
    </div>
  </div>

  <div class="my-button-invitation">
    <div class="form-actions my-tap-container" id="margin-top">
      <%= link_to 'Rerandomize', random_path, class: "btn my-btn my-btn-primary", id: "arrow-issue" %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<%= render 'shared/banner', activities: @activities_names %>

<div class="home-section">
  <h2>Les activités les plus populaires</h2>

  <div class="my-carousel">
    <% @activities_carousel.first(10).each do |activity| %>

      <div class="my-card my-activity-card box-shadow">
        <div class="my-card-div-image">
          <div class="div-image-overlay">
          </div>
          <%= cl_image_tag activity.photos[0].key, crop: :fill %>
          <%# <div class="icon-info"><p>i</p></div> %>
        </div>
        <div class="my-card-div-details display-flex-column">
          <h3><%= activity.name %></h3>
          <div class="display-flex">

            <div class="display-flex-column">
              <div class="card-detail">
                <i class="fas fa-euro-sign"></i>
                <p><%= activity.price_per_head %> (par personne)</p>
              </div>
              <div class="card-detail">
                <i class="fas fa-hourglass-start"></i>
                <p>environ 2h</p>
              </div>
            </div>

            <div class="display-flex-column">
              <div class="card-detail">
                <i class="fas fa-map-marker-alt"></i>
                <p>Lille</p>
              </div>
              <div class="card-detail">
                <%# <i class="fas fa-clock"></i> %>
                <%# <p>rdv à 19h30</p> %>
              </div>
            </div>
          </div>
        </div>
      </div>

    <% end %>

  </div>
</div>

<div class="small-home-section">
  <h2>Les meilleurs avis</h2>
  <%# <div class="my-container"> %>
    <div class="my-carousel-reviews">

      <% @best_reviews.each do |review| %>
        <div class="my-review-card box-shadow">

          <%= cl_image_tag Booking.find(review.booking_id).user.photo.key, class: "avatar" %>
          <%= Booking.find(review.booking_id).user.first_name %>

            <div class="my-review-card-rating">
              <% if [1, 2, 3, 4, 5].include?(review.rating) %>
                <% review.rating.to_i.times do %>
                  <i class="fas fa-star"></i>
                <% end %>
                <% (5 - review.rating.to_i).times do %>
                  <i class="far fa-star"></i>
                <% end %>
              <% else %>
                <% review.rating.to_f.truncate.times do %>
                  <i class="fas fa-star"></i>
                <% end %>
                <i class="fas fa-star-half-alt"></i>
                <% (4 - review.rating.to_f.truncate).times do %>
                  <i class="far fa-star"></i>
                <% end %>
              <% end %>
            </div>

          <div class="my-review-card-content">
            <p><%= review.content %></p>
          </div>
        </div>
      <% end %>

    </div>
  <%# </div> %>
</div>

<%= render 'shared/footer' %>

app/views/pages/random.html.erb
<div class="button-randomize">
    <%= form_with url: custom_activity_path, method: :get, local: true do |f| %>
    <%= f.hidden_field :one_person, id: 'one-person-field', value: true %>
    <%= f.hidden_field :two_people, id: 'two-people-field', value: false %>
    <%= f.hidden_field :aventurier, id: 'aventurier-field', value: true %>
    <%= f.hidden_field :prudent, id: 'prudent-field', value: false %>
    <%= f.hidden_field :max_price, id: 'price-field' %>
    <%= f.hidden_field :outdoor, id: 'outdoor-field', value: false %>
    <%= f.hidden_field :indoor, id: 'indoor-field', value: false %>
    <%= f.hidden_field :sport, id: 'sport-field', value: false %>
    <%= f.hidden_field :manger, id: 'manger-field', value: false  %>
    <%= f.hidden_field :sortir, id: 'sortir-field', value: false %>
    <%= f.hidden_field :nature, id: 'nature-field', value: false %>
    <%= f.hidden_field :bien_etre, id: 'bien_etre-field', value: false %>
    <%= f.hidden_field :se_divertir, id: 'se-divertir-field', value: false %>
  <div class="my-tap-container" id="remove-fixed">
    <%= f.submit 'Randomize!', class: 'my-btn my-btn-primary display-none', id: 'rdm-btn' %>
    <% end %>
  <a href="" class="my-btn my-btn-primary", id="next-btn">SUIVANT</a>
  </div>
</div>

<div class="random-section" id="section-map">
  <div class="map-container-flex">
    <div id="map"
       data-markers="<%= @markers.to_json %>"
       data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      <div id="geolocate">
        <i class="fas fa-location-arrow"></i>
      </div>
      <%# <div class="slide-container">
        <input type="range" min="1" max="10" value="5" step="1" class="slider" id="myRange">
      </div> %>
    </div>
  </div>



    <%# <div class="form-group map-filters">
      <h2><label for="formControlRange">Jusqu'où irais-tu pour randomize?</label></h2>
      <input type="text" class = "hiddenAddress">
      <div class="align">
        <p>10 km</p>
        <input type="range" class="form-control-range" id="formControlRange">
        <p> 1 km</p>
      </div>
    </div>

    <div class="number-participants">
      <div class="one-participant">
        <input type="radio" id="person" name="participants" value="person" class= "one-participant"
               checked>
        <i for="person" class="fas fa-user-circle"></i>
      </div>
      <div class="two-participants">
        <input type="radio" id="people" name="participants" value="people">
        <i for= "people" class="fas fa-user-friends"></i>
      </div>
    </div> %>
    <%# <input value="Suivant" class="my-btn-primary btn-extend" id="next-scroll"> %>
</div>



<div class="my-container">
<div class="mood-form random-section display-none " id="mood-section">
  <h2>ON SE LA JOUE COMMENT ?</h2>
  <div class="mood-images">
    <div class="mood-card img-adventure active-mood-card" id="adventure">
      <%= image_tag "moodadventure.jpg" %>
      <h3>Aventurier</h3>
      <div class="check" id="mood-aventurier">
        <i class="fas fa-check"></i>
      </div>
    </div>
    <div class="mood-card img-shy" id="prudent-card">
      <%= image_tag "moodshy.jpg" %>
      <h3>Prudent</h3>
      <div class="check" id="mood-shy">
        <i class="fas fa-check"></i>
      </div>
    </div>
  </div>

  <div id="mood-sentence">
    <div class="completely-random">
      <%= image_tag "arrowtopleft.png", class: "arrow-top-left" %>
      <p>Totalement au hasard !</p>
    </div>
    <div class="choose-a-little">
      <%= image_tag "arrowtopright.png", class: "arrow-top-right" %>
      <p>Je choisis quand même un peu...</p>
    </div>
  </div>
  <div class="map-controls">
    <div class="number-participants mt-4">
      <div id="one-person" class="d-flex align-items-center active-mood-card">
        <i class="fas fa-user m-3"></i>
        <div class="check" id="check-one-person">
          <i class="fas fa-check"></i>
        </div>
      </div>
      <div id="two-people" class="d-flex align-items-center">
        <i class="fas fa-user-friends m-3"></i>
        <div class="check" id="check-two-people">
          <i class="fas fa-check"></i>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="random-section  display-none form-budget-ext-int mood-form" id="section-custom-1">
  <h2>Quel est ton budget maximal par personne ?</h2>

  <%# <form action="#" method="post"> %>
    <div class="my-form-budget">
      <input type="number" id="max-price" class="input-field" name="max-price" min="0" max="100" value="">
      <i class="fas fa-euro-sign"></i>
    </div>

    <h2>Plutôt intérieur, extérieur ou les deux ?</h2>
    <div class="mood-images">
      <div class="select-indoor-outdoor" id="outdoor-card">
        <%= image_tag "ext.png" %>
        <div class="check" id="select-indoor">
          <i class="fas fa-check"></i>
        </div>
        <h3>Extérieur</h3>
      </div>
      <div class="select-indoor-outdoor" id="indoor-card">
        <%= image_tag "int.png" %>
        <div class="check" id="select-outdoor">
          <i class="fas fa-check"></i>
        </div>
        <h3>Intérieur</h3>
      </div>
    </div>


    <%# <div class="button-next">
      <div class="my-tap-container" id="remove-fixed">
        <a href="#" class="my-btn my-btn-primary">SUIVANT</a>
      </div>
    </div> %>
  <%# </form> %>
  <div class="random-section  display-none" id="section-custom-2">
    <h2>Quel serait ton type d'activité ?</h2>
    <form action="#">

      <div class="category-checkboxes">
        <div>
          <div class="category-checkbox" id="sport-card">
            <div class="sport-background">
              <div class="check" id="categ-sport">
                <i class="fas fa-check"></i>
              </div>
            </div>
            <p>Sport</p>
          </div>

          <div class="category-checkbox" id="manger-card">
            <div class="social-background">
              <div class="check" id="categ-social">
                <i class="fas fa-check"></i>
              </div>
            </div>
            <p>Manger</p>
          </div>
        </div>

        <div>
          <div class="category-checkbox" id="sortir-card">
            <div class="culture-background">
              <div class="check" id="categ-culture">
                <i class="fas fa-check"></i>
              </div>
            </div>
            <p>Sortir</p>
          </div>

          <div class="category-checkbox" id="nature-card">
            <div class="nature-background">
              <div class="check" id="categ-nature">
                <i class="fas fa-check"></i>
              </div>
            </div>
            <p>Nature</p>
          </div>
        </div>


        <div>
          <div class="category-checkbox" id="bien_etre-card">
            <div class="bien_etre-background">
              <div class="check" id="categ-bien_etre">
                <i class="fas fa-check"></i>
              </div>
            </div>
            <p>Bien être</p>
          </div>

          <div class="category-checkbox" id="se-divertir-card">
            <div class="sensation-background">
              <div class="check" id="categ-sensation">
                <i class="fas fa-check"></i>
              </div>
            </div>
            <p>Se divertir</p>
          </div>
        </div>

      </div>
    </form>
  </div>
</div>
</div>