config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/components', to: 'pages#components'
  resources :activities, except: [:index]
  resources :bookings

  get '/profile/my_bookings', to: 'bookings#my_bookings'
  get '/profile/my_bookings/:id', to: 'bookings#show', as: :my_booking

  get '/invitation', to: 'bookings#invitation', as: :invitation

  get '/profile/my_bookings/:booking_id/reviews/new', to: 'reviews#new', as: :new_review
  post'/profile/my_bookings/:booking_id/reviews/', to: 'reviews#create', as: :create_review
  delete '/profile/reviews/:id', to: 'reviews#destroy', as: :destroy_review

  get '/custom_activity', to: 'pages#custom_activity', as: :custom_activity
  get '/random', to: 'pages#random'
  get '/select', to: 'pages#select'
  get '/no_activity', to: 'pages#no_activity', as: :no_activity

  get '/activity/:id', to: 'activities#show' do
    resources :bookings, only: [:new, :create]
  end
  delete '/profile/my_bookings', to: 'bookings#destroy'
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :slots, dependent: :destroy
  has_many :bookings, through: :slots
  has_many_attached :photos

  # validates :name, :address, :price_per_head, :activity_url, :longitude, :latitude, presence: true
  validates :name, :address, :price_per_head, presence: true # removed longitude latitude and activity url

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def new
    @activity = Activity.new
  end

  def show
    @activity = Activity.find(params[:id])
    @slot = @activity.slots.first
    @reveal = false
  end

  def create
    @activity = Activity.new(activity_params)

    if @activity.save
      redirect_to activity_path, notice: "Your activity has been added successfully."
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @activity.update(boat_params)
    if @activity.save
      redirect_to activity_path(@activity), notice: "Your activity has been updated successfully."
    else
      render 'new'
    end
  end

  def destroy
    @activity.destroy

    redirect_to my_activities_path, notice: "Your activity has been deleted successfully."
  end
end

app/views/activities/show.html.erb
<div class="placholder-navbar" style="height:66px"></div>

<div class="container">
<div class="mood-form loader" id="loader">
  <h2>RANDOMIZE TE FAIT DÉCOUVRIR ...</h2>
    <%= image_tag "dice.gif", class: "dice-gif" %>
</div>


<div id="activity-revealed">
  <div class="my-card my-activity-card box-shadow activity-secret">
    <div class="my-card-div-image">
      <% if @activity.instructions %>
        <div class="icon-info" id="#info<%=@activity.id%>"></div>
        <div class = "activity-informations display-none" id="info<%=@activity.id%>">
          <%= @activity.instructions %>
        </div>
      <% end %>
      <div class="div-image-overlay">
        <p>?</p>
        <a class="my-btn my-btn-reveal" id="btn-reveal-activity" title="Révéler">Révéler</a>

      </div>
      <%= cl_image_tag @activity.photos[0].key, crop: :fill %>
    </div>
    <div class="my-card-div-details display-flex-column">
      <div class="hide-name"></div>
      <h3> <%= @activity.name %> </h3>
      <div class="display-flex">

        <div class="display-flex-column">
          <div class="card-detail">
            <i class="fas fa-euro-sign"></i>
            <p> <%= @activity.price_per_head %> (par personne)</p>
          </div>
          <div class="card-detail">
            <i class="fas fa-hourglass-start"></i>
            <p>environ 2h</p>
          </div>
        </div>

        <div class="display-flex-column">
          <div class="card-detail">
            <i class="fas fa-map-marker-alt"></i>
            <p>à 7km</p>
          </div>
          <div class="card-detail">
            <i class="fas fa-clock"></i>
            <p>rdv à 19h30</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="form-actions my-tap-container">
    <%= link_to 'Rerandomize', random_path, class: "btn my-btn my-btn-secondary my-btn-top-left-radius" %>
    <%= link_to 'Réserver', bookings_path(activity_id: @activity, slot_id: @slot, reveal: @reveal, nb_people: params[:nb_people]), method: :post, class: "btn my-btn my-btn-primary my-btn-top-right-radius", id: "btn-booking-reservation" %>
  </div>
</div>